-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCdvVBQ7av9NoeWJt
pfV+O+rKQu0zXypwJplIBkymz++gCgYIKoZIzj0DAQehRANCAAQ8O5FbLeGsxHGZ
+yz1bNkr+x/05ry/dDKTtmXtc9wTgkDv48UgvznX7rkcr3RsHkczqdKBc3ukUYLu
Acwxm5Wi
-----END PRIVATE KEY-----